package task

import (
	"database/sql"
	"errors"
)

type PostgresRepository struct {
	db *sql.DB
}

func NewPostgresRepository(db *sql.DB) *PostgresRepository {
	return &PostgresRepository{
		db: db,
	}
}

func (r *PostgresRepository) Migrate() error {
	query := `
	CREATE TABLE IF NOT EXISTS tasks (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		title TEXT NOT NULL,
		description TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL,
		category TEXT NOT NULL DEFAULT '',
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	);
	`

	_, err := r.db.Exec(query)
	return err
}

func (r *PostgresRepository) Create(task Task) (Task, error) {
	query := `
	INSERT INTO tasks (title, description, status, category, created_at, updated_at)
	VALUES ($1, $2, $3, $4, $5, $6)
	RETURNING id;
	`

	err := r.db.QueryRow(
		query,
		task.Title,
		task.Description,
		task.Status,
		task.Category,
		task.CreatedAt,
		task.UpdatedAt,
	).Scan(&task.ID)

	if err != nil {
		return Task{}, err
	}

	return task, nil
}

func (r *PostgresRepository) GetAll() ([]Task, error) {
	query := `
	SELECT id, title, description, status, category, created_at, updated_at
	FROM tasks
	ORDER BY id;
	`

	rows, err := r.db.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	tasks := []Task{}

	for rows.Next() {
		var task Task

		err := rows.Scan(
			&task.ID,
			&task.Title,
			&task.Description,
			&task.Status,
			&task.Category,
			&task.CreatedAt,
			&task.UpdatedAt,
		)
		if err != nil {
			return nil, err
		}

		tasks = append(tasks, task)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return tasks, nil
}

func (r *PostgresRepository) GetByID(id int) (Task, error) {
	query := `
	SELECT id, title, description, status, category, created_at, updated_at
	FROM tasks
	WHERE id = $1;
	`

	var task Task

	err := r.db.QueryRow(query, id).Scan(
		&task.ID,
		&task.Title,
		&task.Description,
		&task.Status,
		&task.Category,
		&task.CreatedAt,
		&task.UpdatedAt,
	)

	if errors.Is(err, sql.ErrNoRows) {
		return Task{}, ErrTaskNotFound
	}

	if err != nil {
		return Task{}, err
	}

	return task, nil
}

func (r *PostgresRepository) UpdateTask(id int, task Task) (Task, error) {
	query := `
	UPDATE tasks
	SET title = $1,
		description = $2,
		status = $3,
		category = $4,
		updated_at = $5
	WHERE id = $6
	RETURNING id, title, description, status, category, created_at, updated_at;
	`

	var updatedTask Task

	err := r.db.QueryRow(
		query,
		task.Title,
		task.Description,
		task.Status,
		task.Category,
		task.UpdatedAt,
		id,
	).Scan(
		&updatedTask.ID,
		&updatedTask.Title,
		&updatedTask.Description,
		&updatedTask.Status,
		&updatedTask.Category,
		&updatedTask.CreatedAt,
		&updatedTask.UpdatedAt,
	)

	if errors.Is(err, sql.ErrNoRows) {
		return Task{}, ErrTaskNotFound
	}

	if err != nil {
		return Task{}, err
	}

	return updatedTask, nil
}

func (r *PostgresRepository) Remove(id int) error {
	query := `
	DELETE FROM tasks
	WHERE id = $1;
	`

	result, err := r.db.Exec(query, id)
	if err != nil {
		return err
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return err
	}

	if rowsAffected == 0 {
		return ErrTaskNotFound
	}

	return nil
}
